language: d
d: dmd-2.079.0
services: postgresql
before_script:
- psql -c 'create database vonneybot;' -U postgres
- psql -c 'create user f;' -U postgres
- psql -c 'grant all privileges on database vonneybot to f;' -U f
- psql -c 'create table settings (name varchar(64) primary key, value varchar(128));' -U f -d vonneybot
script:
- mv dub.json.for_travis dub.json
- dub