language: d
d: dmd-2.079.0
services: postgresql
env: OPENSSL_VERSION=openssl-1.1.0
before_script:
- psql -c 'create database vonneybot;' -U postgres
- psql -c 'create table settings (name varchar(64) primary key, value varchar(128));' -U postgres -d vonneybot
script:
- mv dub.json.for_travis dub.json
- sed -i s/dbUserName\ =\ \"f\"/dbUserName\ =\ \"postgres\"/ source/app.d
- dub